"""OAuth platform configurations for 50+ platforms.

Each entry defines authorization endpoints, token endpoints, default
scopes, and platform-specific parameters for OAuth 2.0 flows.
"""

from __future__ import annotations

from typing import Any

PLATFORM_CONFIG: dict[str, dict[str, Any]] = {
    "facebook": {
        "auth_endpoint": "https://www.facebook.com/v18.0/dialog/oauth",
        "token_endpoint": "https://graph.facebook.com/v18.0/oauth/access_token",
        "scope_separator": ",",
        "default_scopes": ["pages_read_engagement", "pages_manage_posts", "instagram_basic"],
        "uses_refresh": True,
    },
    "instagram": {
        "auth_endpoint": "https://www.facebook.com/v18.0/dialog/oauth",
        "token_endpoint": "https://graph.facebook.com/v18.0/oauth/access_token",
        "scope_separator": ",",
        "default_scopes": ["instagram_basic", "instagram_content_publish", "pages_read_engagement"],
        "uses_refresh": True,
    },
    "twitter": {
        "auth_endpoint": "https://twitter.com/i/oauth2/authorize",
        "token_endpoint": "https://api.twitter.com/2/oauth2/token",
        "scope_separator": " ",
        "default_scopes": ["tweet.read", "tweet.write", "users.read", "offline.access"],
        "uses_refresh": True,
        "token_endpoint_auth": "basic",
    },
    "linkedin": {
        "auth_endpoint": "https://www.linkedin.com/oauth/v2/authorization",
        "token_endpoint": "https://www.linkedin.com/oauth/v2/accessToken",
        "scope_separator": " ",
        "default_scopes": [
            "r_basicprofile",
            "r_organization_social",
            "w_organization_social",
            "r_liteprofile",
        ],
        "uses_refresh": True,
    },
    "tiktok": {
        "auth_endpoint": "https://www.tiktok.com/v2/auth/authorize/",
        "token_endpoint": "https://open.tiktokapis.com/v2/oauth/token/",
        "scope_separator": ",",
        "default_scopes": ["user.info.basic", "video.publish", "video.list"],
        "uses_refresh": True,
    },
    "youtube": {
        "auth_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_endpoint": "https://oauth2.googleapis.com/token",
        "scope_separator": " ",
        "default_scopes": [
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtube.upload",
        ],
        "uses_refresh": True,
        "access_type": "offline",
        "prompt": "consent",
    },
    "google_ads": {
        "auth_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_endpoint": "https://oauth2.googleapis.com/token",
        "scope_separator": " ",
        "default_scopes": ["https://www.googleapis.com/auth/adwords"],
        "uses_refresh": True,
        "access_type": "offline",
        "prompt": "consent",
    },
    "google_analytics": {
        "auth_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_endpoint": "https://oauth2.googleapis.com/token",
        "scope_separator": " ",
        "default_scopes": ["https://www.googleapis.com/auth/analytics.readonly"],
        "uses_refresh": True,
        "access_type": "offline",
        "prompt": "consent",
    },
    "google_search_console": {
        "auth_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_endpoint": "https://oauth2.googleapis.com/token",
        "scope_separator": " ",
        "default_scopes": ["https://www.googleapis.com/auth/webmasters.readonly"],
        "uses_refresh": True,
        "access_type": "offline",
        "prompt": "consent",
    },
    "google_drive": {
        "auth_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_endpoint": "https://oauth2.googleapis.com/token",
        "scope_separator": " ",
        "default_scopes": [
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/drive.file",
        ],
        "uses_refresh": True,
        "access_type": "offline",
        "prompt": "consent",
    },
    "pinterest": {
        "auth_endpoint": "https://www.pinterest.com/oauth/",
        "token_endpoint": "https://api.pinterest.com/v5/oauth/token",
        "scope_separator": ",",
        "default_scopes": ["boards:read", "pins:read", "pins:write"],
        "uses_refresh": True,
    },
    "reddit": {
        "auth_endpoint": "https://www.reddit.com/api/v1/authorize",
        "token_endpoint": "https://www.reddit.com/api/v1/access_token",
        "scope_separator": " ",
        "default_scopes": ["read", "submit", "identity"],
        "uses_refresh": True,
        "token_endpoint_auth": "basic",
        "duration": "permanent",
    },
    "snapchat": {
        "auth_endpoint": "https://accounts.snapchat.com/accounts/oauth2/auth",
        "token_endpoint": "https://accounts.snapchat.com/accounts/oauth2/token",
        "scope_separator": ",",
        "default_scopes": ["snapchat-marketing-api"],
        "uses_refresh": True,
    },
    "mailchimp": {
        "auth_endpoint": "https://login.mailchimp.com/oauth2/authorize",
        "token_endpoint": "https://login.mailchimp.com/oauth2/token",
        "scope_separator": " ",
        "default_scopes": [""],
        "uses_refresh": False,
    },
    "hubspot_crm": {
        "auth_endpoint": "https://app.hubspot.com/oauth/authorize",
        "token_endpoint": "https://api.hubapi.com/oauth/v1/token",
        "scope_separator": " ",
        "default_scopes": ["oauth", "crm.objects.contacts.read", "crm.objects.contacts.write"],
        "uses_refresh": True,
    },
    "hubspot_email": {
        "auth_endpoint": "https://app.hubspot.com/oauth/authorize",
        "token_endpoint": "https://api.hubapi.com/oauth/v1/token",
        "scope_separator": " ",
        "default_scopes": ["oauth", "content", "forms"],
        "uses_refresh": True,
    },
    "salesforce": {
        "auth_endpoint": "https://login.salesforce.com/services/oauth2/authorize",
        "token_endpoint": "https://login.salesforce.com/services/oauth2/token",
        "scope_separator": " ",
        "default_scopes": ["api", "refresh_token"],
        "uses_refresh": True,
    },
    "pipedrive": {
        "auth_endpoint": "https://oauth.pipedrive.com/oauth/authorize",
        "token_endpoint": "https://oauth.pipedrive.com/oauth/token",
        "scope_separator": ",",
        "default_scopes": ["deals:full", "contacts:full"],
        "uses_refresh": True,
    },
    "slack": {
        "auth_endpoint": "https://slack.com/oauth/v2/authorize",
        "token_endpoint": "https://slack.com/api/oauth.v2.access",
        "scope_separator": ",",
        "default_scopes": ["chat:write", "channels:read", "users:read"],
        "uses_refresh": False,
    },
    "discord": {
        "auth_endpoint": "https://discord.com/api/oauth2/authorize",
        "token_endpoint": "https://discord.com/api/oauth2/token",
        "scope_separator": " ",
        "default_scopes": ["bot", "identify"],
        "uses_refresh": True,
    },
    "asana": {
        "auth_endpoint": "https://app.asana.com/-/oauth_authorize",
        "token_endpoint": "https://app.asana.com/-/oauth_token",
        "scope_separator": ",",
        "default_scopes": ["default"],
        "uses_refresh": True,
    },
    "trello": {
        "auth_endpoint": "https://trello.com/1/authorize",
        "token_endpoint": "https://trello.com/1/OAuthGetAccessToken",
        "scope_separator": ",",
        "default_scopes": ["read", "write"],
        "uses_refresh": False,
    },
    "jira": {
        "auth_endpoint": "https://auth.atlassian.com/authorize",
        "token_endpoint": "https://auth.atlassian.com/oauth/token",
        "scope_separator": " ",
        "default_scopes": ["read:jira-work", "write:jira-work", "read:me"],
        "uses_refresh": True,
        "audience": "api.atlassian.com",
    },
    "notion": {
        "auth_endpoint": "https://api.notion.com/v1/oauth/authorize",
        "token_endpoint": "https://api.notion.com/v1/oauth/token",
        "scope_separator": " ",
        "default_scopes": [],
        "uses_refresh": False,
    },
    "shopify": {
        "auth_endpoint_template": "https://{shop}.myshopify.com/admin/oauth/authorize",
        "token_endpoint_template": "https://{shop}.myshopify.com/admin/oauth/access_token",
        "scope_separator": ",",
        "default_scopes": ["read_products", "read_orders", "read_customers"],
        "uses_refresh": False,
    },
    "stripe": {
        "auth_endpoint": "https://connect.stripe.com/oauth/authorize",
        "token_endpoint": "https://connect.stripe.com/oauth/token",
        "scope_separator": " ",
        "default_scopes": ["read_write"],
        "uses_refresh": False,
    },
    "paypal": {
        "auth_endpoint": "https://www.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize",
        "token_endpoint": "https://api.paypal.com/v1/oauth2/token",
        "scope_separator": " ",
        "default_scopes": ["openid", "profile", "email"],
        "uses_refresh": True,
        "token_endpoint_auth": "basic",
    },
    "square": {
        "auth_endpoint": "https://connect.squareup.com/oauth2/authorize",
        "token_endpoint": "https://connect.squareup.com/oauth2/token",
        "scope_separator": " ",
        "default_scopes": ["ITEMS_READ", "ORDERS_READ", "PAYMENTS_READ"],
        "uses_refresh": True,
    },
    "figma": {
        "auth_endpoint": "https://www.figma.com/oauth",
        "token_endpoint": "https://www.figma.com/api/oauth/token",
        "scope_separator": ",",
        "default_scopes": ["file_read"],
        "uses_refresh": False,
    },
    "canva": {
        "auth_endpoint": "https://www.canva.com/api/oauth/authorize",
        "token_endpoint": "https://api.canva.com/rest/v1/oauth/token",
        "scope_separator": " ",
        "default_scopes": ["design:read", "design:write"],
        "uses_refresh": True,
    },
    "activecampaign": {
        "auth_endpoint": "",
        "token_endpoint": "",
        "scope_separator": " ",
        "default_scopes": [],
        "uses_refresh": False,
        "api_key_only": True,
    },
    "convertkit": {
        "auth_endpoint": "https://app.convertkit.com/oauth/authorize",
        "token_endpoint": "https://api.convertkit.com/oauth/token",
        "scope_separator": " ",
        "default_scopes": [],
        "uses_refresh": True,
    },
    "zoho_crm": {
        "auth_endpoint": "https://accounts.zoho.com/oauth/v2/auth",
        "token_endpoint": "https://accounts.zoho.com/oauth/v2/token",
        "scope_separator": ",",
        "default_scopes": ["ZohoCRM.modules.ALL", "ZohoCRM.users.ALL"],
        "uses_refresh": True,
    },
    "microsoft_ads": {
        "auth_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scope_separator": " ",
        "default_scopes": ["https://ads.microsoft.com/ads.manage"],
        "uses_refresh": True,
    },
    "microsoft_teams": {
        "auth_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scope_separator": " ",
        "default_scopes": ["https://graph.microsoft.com/ChannelMessage.Send"],
        "uses_refresh": True,
    },
    "onedrive": {
        "auth_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scope_separator": " ",
        "default_scopes": ["https://graph.microsoft.com/Files.ReadWrite"],
        "uses_refresh": True,
    },
    "dropbox": {
        "auth_endpoint": "https://www.dropbox.com/oauth2/authorize",
        "token_endpoint": "https://api.dropboxapi.com/oauth2/token",
        "scope_separator": " ",
        "default_scopes": [],
        "uses_refresh": True,
        "token_access_type": "offline",
    },
    "monday": {
        "auth_endpoint": "https://auth.monday.com/oauth2/authorize",
        "token_endpoint": "https://auth.monday.com/oauth2/token",
        "scope_separator": " ",
        "default_scopes": [],
        "uses_refresh": True,
    },
}
